<?php
/**
* Implementation of hook_menu().
*/

//require ("DAL.php");

function module1_menu() {
$items = array();

$items['module1'] = array(
'title' => 'Module 1',
'page callback' => 'dbExterne',
'access arguments' => array('access content'),
'type' => MENU_CALLBACK,
);
$items['module1/contact/new'] = array(
'title' => 'Module 1',
'page callback' => 'module1_contact_new',
'access arguments' => array('access content'),
'type' => MENU_CALLBACK,
);
$items['module1/contact/delete/%'] = array(
'title' => 'Module 1',
'page callback' => 'module1_contact_delete',
'access arguments' => array('access content'),
'type' => MENU_CALLBACK,
);
$items['module1/contact/list'] = array(
'title' => 'Module 1',
'page callback' => 'module1_contact_list',
'access arguments' => array('access content'),
'type' => MENU_CALLBACK,
);
$items['module1/contact/edit/%'] = array(
'title' => 'Module 1',
'page callback' => 'module1_contact_edit',
'access arguments' => array('access content'),
'type' => MENU_CALLBACK,
);


$items['module1/contact/testdalselect'] = array(
'title' => 'Module 1',
'page callback' => 'module1_contact_testdalselect',
'access arguments' => array('access content'),
'type' => MENU_CALLBACK,
);

$items['module1/contact/testdaldelete'] = array(
'title' => 'Module 1',
'page callback' => 'module1_contact_testdalselect',
'access arguments' => array('access content'),
'type' => MENU_CALLBACK,
);

$items['module1/contact/testbl'] = array(
'title' => 'Module 1',
'page callback' => 'module1_contact_testbl',
'access arguments' => array('access content'),
'type' => MENU_CALLBACK,
);

return $items;
}

function module1_contact_list() {
$vars = 'Affiche les contacts';

return $vars;
}
function module1_contact_new() {
$vars = 'Ajouter un contact';

$config = array(
 'db' => 'commercial',
 'table' => 'contact',
 'idKey' => 'cid',
 'autoIncrement' => TRUE,
 'defaultOrder' => array('nom' => 'asc'),
 'rowClass' => 'stdClass',
);

$dal = new DAL($config);

$tab = array(
	'contact1' => array(
		'cid' => '4',
		'nom' => 'nom1',
		'prenom' => 'prenom1',
		'adresse' => 'adresse1',
		'telephone' => 0612345678,
 		'email' => 'email1'
	)
);

foreach ($tab as $contact)
{
	$dal->insert($contact);
}

return $vars;
}

function module1_contact_delete($id) {
$vars = 'Supprimer un contact';

return $vars;
}

function module1_contact_edit($id) {
$vars = 'Editer un contact';

return $vars;
}

function module1_contact_testdalselect() {
$vars = 'Test de selection de contact avec un objet DAL';

return $vars;
}

function module1_contact_testdaldelete() {
$vars = 'Test de suppression de contact avec un objet DAL';

return $vars;
}

function module1_contact_testbl() {
$vars = 'Test de mes objets métiers';

return $vars;
}
